services:
  - type: web
    name: websocket-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    autoDeploy: true
